### ISSUE TITLE
[question]: Is this PROD ready?

### ISSUE THREAD

**Issue by juandiago** [OneSignal/onesignal-python-api#4]
### How can we help?

Hey guys, saw that this is now the official python onesignal sdk, was curious if this package is PROD ready and if we're safe to use it in our projects? 

P.D.: currently using https://pypi.org/project/onesignal-sdk/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kesheshyan** [comment]
Hey @juandiago ! Thanks for the question. We just released this library into PROD, but haven't announced it yet. You are free to try it. This library is autogenerated by our internal fork of https://github.com/OpenAPITools/openapi-generator tool.  It is tested pretty well but still may contain some minor bugs. We would really like to hear your feedback on this client so that we can improve it!

**Comment by kesheshyan** [comment]
Hey @juandiago ! Thanks for the question. We just released this library into PROD, but haven't announced it yet. You are free to try it. This library is autogenerated by our internal fork of https://github.com/OpenAPITools/openapi-generator tool. It is tested pretty well but still may contain some minor bugs. We would really like to hear your feedback on this client so that we can improve it!

**Comment by juandiago** [comment]
Tks! Will do and report back any feedback...
